version: '2'

services:
  graph_db:
    image: mysql:5.7
    ports:
      - "33060:3306"
    hostname: graph_db
    restart: always
    volumes:
      - ./graph/mysql/conf.d:/etc/mysql/conf.d
      - ../mysql/graph/data:/var/lib/mysql
    environment:
      - MYSQL_NAME=graph_db
      - MYSQL_DATABASE=graph_db
      - MYSQL_USER=graph_db
      - MYSQL_PASSWORD=graph_db
      - MYSQL_ROOT_PASSWORD=graph_db

  table_db:
    image: mysql:5.7
    ports:
      - "33061:3306"
    hostname: table_db
    restart: always
    volumes:
      - ./table/mysql/conf.d:/etc/mysql/conf.d
      - ../mysql/table/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --explicit_defaults_for_timestamp=1
    environment:
      - MYSQL_NAME=table_db
      - MYSQL_DATABASE=table_db
      - MYSQL_USER=table_db
      - MYSQL_PASSWORD=table_db
      - MYSQL_ROOT_PASSWORD=table_db

  customer_api_db:
    image: mysql:5.7
    ports:
      - "33062:3306"
    hostname: customer_api_db
    restart: always
    volumes:
      - ./customer_api_db/mysql/conf.d:/etc/mysql/conf.d
      - ../mysql/customer_api_db/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --explicit_defaults_for_timestamp=1
    environment:
      - MYSQL_NAME=customer_api_db
      - MYSQL_DATABASE=customer_api_db
      - MYSQL_USER=customer_api_db
      - MYSQL_PASSWORD=customer_api_db
      - MYSQL_ROOT_PASSWORD=customer_api_db

  zabbix_api_db:
    image: mysql:5.7
    ports:
      - "33063:3306"
    hostname: zabbix_api_db
    restart: always
    volumes:
      - ./zabbix_api_db/mysql/conf.d:/etc/mysql/conf.d
      - ../mysql/zabbix_api_db/data:/var/lib/mysql
    environment:
      - MYSQL_NAME=zabbix_api_db
      - MYSQL_DATABASE=zabbix_api_db
      - MYSQL_USER=zabbix_api_db
      - MYSQL_PASSWORD=zabbix_api_db
      - MYSQL_ROOT_PASSWORD=zabbix_api_db

  nginx:
    image: nginx
    ports:
      - "80:80" 
    hostname: nginx
    volumes:
      - ./nginx/html:/code
      - ./nginx/conf.d:/etc/nginx/conf.d/
   
    #links:
      #- customer_api
    #  - zabbix_api  

  graph:
    #image: django
    build: ./graph
    #env_file: ./django/env_django
    #command: python3 manage.py startapp app
    command: python3 manage.py makemigrations
    command: python3 manage.py migrate
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./graph:/code
    ports:
      - "8002:8000"
    links:
      - graph_db
      - table
      - customer_api
      - zabbix_api
    depends_on:
      - graph_db
  
  table:
     #image: django
    build: ./table
    #env_file: django/env_django
    #command: mkdir -p /code/table/static
    #command: wget https://github.com/twbs/bootstrap/releases/download/v4.0.0-alpha.6/bootstrap-4.0.0-alpha.6-dist.zip -P /code/table/static
    #command: unzip /code/table/static/bootstrap-4.0.0-alpha.6-dist.zip
    #command: cp -a /code/table/static/bootstrap-4.0.0-alpha.6-dist/* /code/table/static
    #command: rm -rf /code/table/static/bootstrap-4.0.0-alpha.6-dist
    command: python3 manage.py startapp app
    #command: python3 manage.py makemigrations
    #command: python3 manage.py migrate
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./table:/code
    ports:
      - "8001:8000"
    links:
      - table_db
    depends_on:
      - table_db
    
  customer_api:
    #image: django
    build: ./customer_api
    #env_file: ./django/env_django
    #command: python3 manage.py startapp api
    command: python3 manage.py makemigrations
    command: python3 manage.py migrate
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./customer_api:/code
    ports:
      - "8002:8000"
    links:
      - customer_api_db
    depends_on:
      - customer_api_db

  zabbix_api:
    build: ./zabbix_api
    ports:
      - "8000:8000"
    hostname: zabbix_api
    volumes:
      - ./zabbix_api:/code
    command: gunicorn -b 0.0.0.0:8000 -w 4  resource:app
    depends_on: 
      - nginx
      - customer_api
    links:
      - nginx
      - customer_api

#  zabbix_api:
    #image: django
#    build: ./zabbix_api
    #env_file: django/env_django
#    command: python3 manage.py startapp api 
#    command: python3 manage.py makemigrations
#    command: python3 manage.py migrate
#    command: python3 manage.py runserver 0.0.0.0:8000
#    volumes: 
#      - ./zabbix_api:/code
#    ports:
#      - "8003:8000"
#    links:
#      - zabbix_api_db
#    depends_on:
#      - zabbix_api_db
